import { Opportunity } from '@/types/opportunity';

export const mockOpportunities: Opportunity[] = [
  {
    id: '1',
    name: 'Google Summer of Code 2025',
    organizer: 'Google',
    description: 'A global, online program focused on bringing new contributors into open source software development. GSoC Contributors work with an open source organization on a 12+ week programming project.',
    category: 'opensource',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-03-10'),
    applicationEnd: new Date('2025-04-02'),
    eventStart: new Date('2025-05-27'),
    eventEnd: new Date('2025-08-25'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['18+ years old', 'Enrolled in post-secondary education', 'First-time or returning contributor'],
    techStack: ['Various'],
    domains: ['Open Source', 'Web Development', 'AI/ML', 'Systems Programming'],
    stipend: '$1,500 - $6,600 based on project size',
    selectionCriteria: 'Proposal quality, contributions to org, communication skills',
    officialLink: 'https://summerofcode.withgoogle.com/',
    applicationLink: 'https://summerofcode.withgoogle.com/',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Google_Summer_of_Code_logo_%282023%29.png/220px-Google_Summer_of_Code_logo_%282023%29.png',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '9',
    name: 'Google STEP Internship (India)',
    organizer: 'Google',
    description:
      'Summer Trainee Engineering Program (STEP) for first and second year undergraduate students interested in software engineering.',
    category: 'internship',
    mode: 'hybrid',
    level: 'beginner',
    applicationStart: new Date('2025-01-01'),
    applicationEnd: new Date('2025-02-15'),
    eventStart: new Date('2025-05-01'),
    eventEnd: new Date('2025-07-31'),
    location: 'Bangalore / Hyderabad',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['First or second year B.Tech/B.E. students', 'Strong programming fundamentals'],
    techStack: ['C++', 'Java', 'Python'],
    domains: ['Systems Programming', 'Web Development'],
    stipend: 'Competitive internship stipend',
    selectionCriteria: 'Online assessments and interviews',
    officialLink: 'https://careers.google.com/programs/step/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '10',
    name: 'GitHub Campus Expert',
    organizer: 'GitHub',
    description:
      'Program for student leaders to build technical communities on campus with training, resources, and mentorship.',
    category: 'fellowship',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-03-01'),
    applicationEnd: new Date('2025-03-31'),
    eventStart: new Date('2025-04-15'),
    eventEnd: new Date('2025-10-15'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['University students', 'Active in campus community'],
    techStack: ['Git', 'GitHub'],
    domains: ['Open Source', 'DevOps'],
    prizes: 'Training, swag, community budget',
    selectionCriteria: 'Application, video, community impact',
    officialLink: 'https://education.github.com/experts',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '11',
    name: 'ETHIndia',
    organizer: 'Devfolio',
    description:
      'India’s premier Ethereum hackathon bringing builders together to work on DeFi, DAOs, and Web3.',
    category: 'hackathon',
    mode: 'offline',
    level: 'intermediate',
    applicationStart: new Date('2025-08-01'),
    applicationEnd: new Date('2025-09-01'),
    eventStart: new Date('2025-12-05'),
    eventEnd: new Date('2025-12-07'),
    location: 'Bengaluru, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['Students and professionals', 'Solo or team participation'],
    techStack: ['Solidity', 'Ethereum', 'Web3'],
    domains: ['Blockchain'],
    prizes: '$100,000+ in prizes and grants',
    selectionCriteria: 'Project innovation, technical depth, usefulness',
    officialLink: 'https://ethindia.co/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '12',
    name: 'Google Cloud Ready Facilitator Program',
    organizer: 'Google Cloud',
    description:
      'Hands-on program for students in India to learn Google Cloud through quests, labs, and swags.',
    category: 'fellowship',
    mode: 'online',
    level: 'beginner',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-02-28'),
    eventStart: new Date('2025-03-15'),
    eventEnd: new Date('2025-06-15'),
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['College students in India'],
    techStack: ['Google Cloud', 'Kubernetes', 'BigQuery'],
    domains: ['Cloud Computing', 'Data Science'],
    prizes: 'Swag, certificates, leaderboard recognition',
    selectionCriteria: 'Completion of labs and quests',
    officialLink: 'https://events.withgoogle.com/google-cloud-ready-facilitator-program/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '2',
    name: 'MLH Global Hack Week',
    organizer: 'Major League Hacking',
    description: 'A week-long celebration of hacking with daily challenges, workshops, and mini-hackathons. Connect with hackers worldwide and build cool projects!',
    category: 'hackathon',
    mode: 'online',
    level: 'beginner',
    applicationStart: new Date('2025-01-15'),
    applicationEnd: new Date('2025-02-01'),
    eventStart: new Date('2025-02-03'),
    eventEnd: new Date('2025-02-09'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['Students', 'Recent graduates'],
    techStack: ['Any'],
    domains: ['Web Development', 'AI/ML', 'Game Development'],
    prizes: 'Swag, prizes for daily challenges',
    officialLink: 'https://ghw.mlh.io/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '3',
    name: 'Smart India Hackathon 2025',
    organizer: 'Ministry of Education, India',
    description: 'India\'s largest hackathon aimed at solving real-world problems faced by various ministries and departments of the government.',
    category: 'hackathon',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-06-01'),
    applicationEnd: new Date('2025-07-15'),
    eventStart: new Date('2025-12-01'),
    eventEnd: new Date('2025-12-02'),
    location: 'Multiple nodal centers across India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['Engineering students', 'Teams of 6 members'],
    techStack: ['Various'],
    domains: ['IoT', 'AI/ML', 'Web Development', 'Mobile Development'],
    prizes: '₹1,00,000 per winning team',
    selectionCriteria: 'Innovation, feasibility, impact, technical complexity',
    officialLink: 'https://www.sih.gov.in/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '4',
    name: 'GitHub Externship',
    organizer: 'GitHub',
    description: 'A 3-month remote externship program for students in India to work on open-source projects with GitHub mentors.',
    category: 'internship',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-02-28'),
    eventStart: new Date('2025-04-01'),
    eventEnd: new Date('2025-06-30'),
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['Engineering students in India', '2nd or 3rd year preferred'],
    techStack: ['Git', 'GitHub', 'Various programming languages'],
    domains: ['Open Source', 'DevOps', 'Web Development'],
    stipend: '₹50,000/month',
    selectionCriteria: 'GitHub profile, open source contributions, technical skills',
    officialLink: 'https://github.com/externship',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '5',
    name: 'LFX Mentorship Program',
    organizer: 'Linux Foundation',
    description: 'A remote mentorship program where participants gain real-world experience working on open source projects.',
    category: 'opensource',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-02-15'),
    applicationEnd: new Date('2025-03-15'),
    eventStart: new Date('2025-06-01'),
    eventEnd: new Date('2025-08-31'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['18+ years old', 'Students or professionals'],
    techStack: ['Kubernetes', 'Cloud Native', 'Linux'],
    domains: ['Open Source', 'Cloud Computing', 'DevOps'],
    stipend: '$3,000 - $6,600',
    officialLink: 'https://lfx.linuxfoundation.org/tools/mentorship/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '6',
    name: 'Outreachy',
    organizer: 'Software Freedom Conservancy',
    description: 'Internships in open source and open science for people subject to systemic bias and underrepresented in tech.',
    category: 'fellowship',
    mode: 'online',
    level: 'beginner',
    applicationStart: new Date('2025-01-15'),
    applicationEnd: new Date('2025-02-25'),
    eventStart: new Date('2025-05-26'),
    eventEnd: new Date('2025-08-22'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['Underrepresented groups in tech', 'New to open source welcome'],
    techStack: ['Various'],
    domains: ['Open Source', 'Web Development', 'Data Science'],
    stipend: '$7,000',
    selectionCriteria: 'Contribution period performance, proposal quality',
    officialLink: 'https://www.outreachy.org/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '7',
    name: 'HackMIT 2025',
    organizer: 'MIT',
    description: 'MIT\'s annual hackathon bringing together 1000+ hackers to build creative projects over 24 hours.',
    category: 'hackathon',
    mode: 'offline',
    level: 'advanced',
    applicationStart: new Date('2025-07-01'),
    applicationEnd: new Date('2025-08-15'),
    eventStart: new Date('2025-09-20'),
    eventEnd: new Date('2025-09-21'),
    location: 'MIT Campus, Cambridge, MA',
    country: 'USA',
    isIndiaFocused: false,
    eligibility: ['University students worldwide', 'Travel reimbursements available'],
    techStack: ['Any'],
    domains: ['AI/ML', 'Web Development', 'Mobile Development', 'Blockchain'],
    prizes: '$10,000+ in prizes',
    officialLink: 'https://hackmit.org/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '8',
    name: 'Microsoft ENGAGE',
    organizer: 'Microsoft',
    description: 'A mentorship program for Indian engineering students to learn from Microsoft engineers and build projects.',
    category: 'internship',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-04-01'),
    applicationEnd: new Date('2025-04-30'),
    eventStart: new Date('2025-05-15'),
    eventEnd: new Date('2025-07-15'),
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['2nd/3rd year engineering students in India'],
    techStack: ['Azure', 'C#', '.NET', 'React'],
    domains: ['Cloud Computing', 'AI/ML', 'Web Development'],
    selectionCriteria: 'Resume screening, coding assessment, interviews',
    officialLink: 'https://microsoft.acehacker.com/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  // Additional Hackathons
  {
    id: '13',
    name: 'Hack the North',
    organizer: 'University of Waterloo',
    description: 'Canada\'s biggest hackathon bringing together 1000+ students from around the world.',
    category: 'hackathon',
    mode: 'offline',
    level: 'intermediate',
    applicationStart: new Date('2025-07-01'),
    applicationEnd: new Date('2025-08-15'),
    eventStart: new Date('2025-09-13'),
    eventEnd: new Date('2025-09-15'),
    location: 'Waterloo, Canada',
    country: 'Canada',
    isIndiaFocused: false,
    eligibility: ['University students', 'Travel reimbursements available'],
    techStack: ['Any'],
    domains: ['Web Development', 'AI/ML', 'Mobile Development'],
    prizes: '$50,000+ in prizes',
    officialLink: 'https://hackthenorth.com/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '14',
    name: 'Hack36',
    organizer: 'MNNIT Allahabad',
    description: 'India\'s oldest student-run hackathon, 36 hours of innovation and coding.',
    category: 'hackathon',
    mode: 'offline',
    level: 'intermediate',
    applicationStart: new Date('2025-08-01'),
    applicationEnd: new Date('2025-09-15'),
    eventStart: new Date('2025-10-18'),
    eventEnd: new Date('2025-10-20'),
    location: 'MNNIT Allahabad, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['College students', 'Teams of 2-4 members'],
    techStack: ['Any'],
    domains: ['Web Development', 'AI/ML', 'IoT', 'Blockchain'],
    prizes: '₹5,00,000+ in prizes',
    officialLink: 'https://hack36.com/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '15',
    name: 'HackHarvard',
    organizer: 'Harvard University',
    description: 'Harvard\'s annual hackathon attracting top talent from around the world.',
    category: 'hackathon',
    mode: 'offline',
    level: 'advanced',
    applicationStart: new Date('2025-08-15'),
    applicationEnd: new Date('2025-09-30'),
    eventStart: new Date('2025-11-01'),
    eventEnd: new Date('2025-11-03'),
    location: 'Harvard University, Cambridge, MA',
    country: 'USA',
    isIndiaFocused: false,
    eligibility: ['University students worldwide'],
    techStack: ['Any'],
    domains: ['AI/ML', 'Web Development', 'Mobile Development', 'Blockchain'],
    prizes: '$30,000+ in prizes',
    officialLink: 'https://hackharvard.io/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '16',
    name: 'HackDTU',
    organizer: 'Delhi Technological University',
    description: 'DTU\'s annual hackathon promoting innovation and entrepreneurship.',
    category: 'hackathon',
    mode: 'offline',
    level: 'intermediate',
    applicationStart: new Date('2025-09-01'),
    applicationEnd: new Date('2025-10-15'),
    eventStart: new Date('2025-11-15'),
    eventEnd: new Date('2025-11-17'),
    location: 'DTU, New Delhi, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['College students', 'Teams of 2-4'],
    techStack: ['Any'],
    domains: ['Web Development', 'AI/ML', 'IoT', 'Mobile Development'],
    prizes: '₹3,00,000+ in prizes',
    officialLink: 'https://hackdtu.tech/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '17',
    name: 'CodeChef SnackDown',
    organizer: 'CodeChef',
    description: 'Global programming contest with teams competing in elimination rounds.',
    category: 'hackathon',
    mode: 'online',
    level: 'advanced',
    applicationStart: new Date('2025-04-01'),
    applicationEnd: new Date('2025-05-15'),
    eventStart: new Date('2025-06-01'),
    eventEnd: new Date('2025-07-31'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['Programmers worldwide', 'Teams of 2'],
    techStack: ['C++', 'Java', 'Python'],
    domains: ['Algorithms', 'Data Structures', 'Competitive Programming'],
    prizes: '$20,000+ in prizes',
    officialLink: 'https://www.codechef.com/snackdown',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '18',
    name: 'HackNITR',
    organizer: 'NIT Rourkela',
    description: '36-hour hackathon at NIT Rourkela fostering innovation and creativity.',
    category: 'hackathon',
    mode: 'offline',
    level: 'intermediate',
    applicationStart: new Date('2025-09-15'),
    applicationEnd: new Date('2025-10-30'),
    eventStart: new Date('2025-11-22'),
    eventEnd: new Date('2025-11-24'),
    location: 'NIT Rourkela, Odisha, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['College students', 'Teams of 2-4'],
    techStack: ['Any'],
    domains: ['Web Development', 'AI/ML', 'IoT', 'Blockchain'],
    prizes: '₹2,00,000+ in prizes',
    officialLink: 'https://hacknitr.tech/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  // Additional Internships
  {
    id: '19',
    name: 'Amazon SDE Internship',
    organizer: 'Amazon',
    description: 'Software Development Engineer internship for students to work on real-world projects at Amazon.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-01-15'),
    applicationEnd: new Date('2025-03-15'),
    eventStart: new Date('2025-05-15'),
    eventEnd: new Date('2025-08-15'),
    location: 'Bangalore, Hyderabad, Chennai',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Strong CS fundamentals', 'DSA knowledge'],
    techStack: ['Java', 'Python', 'AWS', 'React'],
    domains: ['Web Development', 'Cloud Computing', 'Systems Programming'],
    stipend: '₹60,000-80,000/month',
    selectionCriteria: 'Online assessment, technical interviews',
    officialLink: 'https://www.amazon.jobs/en/teams/internships-for-students',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '20',
    name: 'Microsoft SWE Internship',
    organizer: 'Microsoft',
    description: 'Software Engineering internship at Microsoft India Development Center.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-03-31'),
    eventStart: new Date('2025-05-01'),
    eventEnd: new Date('2025-07-31'),
    location: 'Hyderabad, Bangalore',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Strong programming skills'],
    techStack: ['C#', '.NET', 'Azure', 'React'],
    domains: ['Cloud Computing', 'Web Development', 'AI/ML'],
    stipend: '₹70,000-90,000/month',
    selectionCriteria: 'Coding rounds, technical interviews',
    officialLink: 'https://careers.microsoft.com/us/en/internship',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '21',
    name: 'Goldman Sachs Engineering Internship',
    organizer: 'Goldman Sachs',
    description: 'Engineering internship in financial technology and software development.',
    category: 'internship',
    mode: 'hybrid',
    level: 'advanced',
    applicationStart: new Date('2025-01-01'),
    applicationEnd: new Date('2025-02-28'),
    eventStart: new Date('2025-06-01'),
    eventEnd: new Date('2025-08-31'),
    location: 'Bangalore, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E./M.Tech students', 'Strong algorithms knowledge'],
    techStack: ['Java', 'Python', 'C++'],
    domains: ['Systems Programming', 'Data Science', 'Algorithms'],
    stipend: '₹1,00,000+/month',
    selectionCriteria: 'Coding test, technical interviews',
    officialLink: 'https://www.goldmansachs.com/careers/students/programs/india/engineering.html',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '22',
    name: 'Adobe Research Internship',
    organizer: 'Adobe',
    description: 'Research internship for students interested in computer graphics, AI, and creative technologies.',
    category: 'internship',
    mode: 'hybrid',
    level: 'advanced',
    applicationStart: new Date('2025-01-15'),
    applicationEnd: new Date('2025-03-15'),
    eventStart: new Date('2025-05-15'),
    eventEnd: new Date('2025-08-15'),
    location: 'Noida, Bangalore',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['M.Tech/PhD students', 'Research background preferred'],
    techStack: ['C++', 'Python', 'Machine Learning'],
    domains: ['AI/ML', 'Computer Graphics', 'Data Science'],
    stipend: '₹80,000-1,20,000/month',
    selectionCriteria: 'Research proposal, technical interviews',
    officialLink: 'https://research.adobe.com/adobe-research-internship-program/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '23',
    name: 'Flipkart Tech Internship',
    organizer: 'Flipkart',
    description: 'Technology internship working on e-commerce platforms and scalable systems.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-03-31'),
    eventStart: new Date('2025-05-01'),
    eventEnd: new Date('2025-07-31'),
    location: 'Bangalore, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Strong CS fundamentals'],
    techStack: ['Java', 'React', 'Node.js', 'MongoDB'],
    domains: ['Web Development', 'Systems Programming', 'Data Science'],
    stipend: '₹50,000-70,000/month',
    selectionCriteria: 'Online coding test, technical interviews',
    officialLink: 'https://www.flipkartcareers.com/#!/joblist',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '24',
    name: 'Razorpay Internship',
    organizer: 'Razorpay',
    description: 'Internship opportunity to work on payment infrastructure and fintech solutions.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-02-15'),
    applicationEnd: new Date('2025-04-15'),
    eventStart: new Date('2025-05-15'),
    eventEnd: new Date('2025-08-15'),
    location: 'Bangalore, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Strong problem-solving skills'],
    techStack: ['Python', 'React', 'Node.js', 'PostgreSQL'],
    domains: ['Web Development', 'Systems Programming', 'Fintech'],
    stipend: '₹40,000-60,000/month',
    selectionCriteria: 'Coding challenge, technical interviews',
    officialLink: 'https://razorpay.com/jobs/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '25',
    name: 'Uber Software Engineering Internship',
    organizer: 'Uber',
    description: 'Software engineering internship working on transportation and mobility solutions.',
    category: 'internship',
    mode: 'hybrid',
    level: 'advanced',
    applicationStart: new Date('2025-01-01'),
    applicationEnd: new Date('2025-02-28'),
    eventStart: new Date('2025-05-15'),
    eventEnd: new Date('2025-08-15'),
    location: 'Bangalore, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E./M.Tech students', 'Strong algorithms'],
    techStack: ['Python', 'Go', 'React', 'Kubernetes'],
    domains: ['Systems Programming', 'Web Development', 'Mobile Development'],
    stipend: '₹90,000-1,10,000/month',
    selectionCriteria: 'Coding rounds, system design, interviews',
    officialLink: 'https://www.uber.com/careers/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '26',
    name: 'Atlassian Internship',
    organizer: 'Atlassian',
    description: 'Software engineering internship working on developer tools and collaboration platforms.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-03-31'),
    eventStart: new Date('2025-05-01'),
    eventEnd: new Date('2025-08-31'),
    location: 'Bangalore, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Strong CS fundamentals'],
    techStack: ['Java', 'React', 'Python', 'AWS'],
    domains: ['Web Development', 'DevOps', 'Systems Programming'],
    stipend: '₹60,000-80,000/month',
    selectionCriteria: 'Online assessment, technical interviews',
    officialLink: 'https://www.atlassian.com/company/careers',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  // Additional Open Source Programs
  {
    id: '27',
    name: 'Season of Docs',
    organizer: 'Google',
    description: 'Program bringing technical writers and open source projects together.',
    category: 'opensource',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-04-15'),
    applicationEnd: new Date('2025-05-15'),
    eventStart: new Date('2025-06-15'),
    eventEnd: new Date('2025-11-15'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['Technical writers', 'Open source enthusiasts'],
    techStack: ['Markdown', 'Git', 'Documentation tools'],
    domains: ['Open Source', 'Technical Writing'],
    stipend: '$3,000 - $6,000',
    officialLink: 'https://developers.google.com/season-of-docs',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '28',
    name: 'Hacktoberfest',
    organizer: 'DigitalOcean',
    description: 'Month-long celebration of open source software. Make 4 pull requests to win swag.',
    category: 'opensource',
    mode: 'online',
    level: 'beginner',
    applicationStart: new Date('2025-09-15'),
    applicationEnd: new Date('2025-10-31'),
    eventStart: new Date('2025-10-01'),
    eventEnd: new Date('2025-10-31'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['Anyone', 'GitHub account'],
    techStack: ['Any'],
    domains: ['Open Source'],
    prizes: 'Limited edition t-shirt and swag',
    officialLink: 'https://hacktoberfest.com/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '29',
    name: 'CNCF Mentorship',
    organizer: 'Cloud Native Computing Foundation',
    description: 'Mentorship program for contributing to CNCF projects like Kubernetes, Prometheus, etc.',
    category: 'opensource',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-03-01'),
    applicationEnd: new Date('2025-04-15'),
    eventStart: new Date('2025-05-01'),
    eventEnd: new Date('2025-08-31'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['Students and professionals', 'Interest in cloud native'],
    techStack: ['Go', 'Kubernetes', 'Docker', 'Prometheus'],
    domains: ['Open Source', 'Cloud Computing', 'DevOps'],
    stipend: '$3,000 - $5,000',
    officialLink: 'https://www.cncf.io/mentoring/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '30',
    name: 'Mozilla Open Source Support',
    organizer: 'Mozilla',
    description: 'Program supporting contributors to Mozilla open source projects.',
    category: 'opensource',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-03-31'),
    eventStart: new Date('2025-04-15'),
    eventEnd: new Date('2025-09-15'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['Open source contributors', 'Mozilla project interest'],
    techStack: ['Rust', 'JavaScript', 'Python', 'C++'],
    domains: ['Open Source', 'Web Development', 'Systems Programming'],
    stipend: '$3,000 - $6,000',
    officialLink: 'https://www.mozilla.org/en-US/contribute/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '31',
    name: 'Hyperledger Mentorship',
    organizer: 'Linux Foundation',
    description: 'Mentorship program for blockchain and distributed ledger technologies.',
    category: 'opensource',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-03-15'),
    applicationEnd: new Date('2025-04-30'),
    eventStart: new Date('2025-06-01'),
    eventEnd: new Date('2025-09-30'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['Students and professionals', 'Blockchain interest'],
    techStack: ['Go', 'JavaScript', 'Solidity'],
    domains: ['Open Source', 'Blockchain'],
    stipend: '$3,000 - $5,000',
    officialLink: 'https://wiki.hyperledger.org/display/INTERN',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  // Additional Fellowships
  {
    id: '32',
    name: 'Thiel Fellowship',
    organizer: 'Thiel Foundation',
    description: 'Two-year fellowship for young entrepreneurs to build companies instead of attending college.',
    category: 'fellowship',
    mode: 'hybrid',
    level: 'advanced',
    applicationStart: new Date('2025-01-01'),
    applicationEnd: new Date('2025-03-31'),
    eventStart: new Date('2025-06-01'),
    eventEnd: new Date('2027-06-01'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['22 years or younger', 'Entrepreneurial vision'],
    techStack: ['Any'],
    domains: ['Entrepreneurship', 'Startups'],
    stipend: '$100,000',
    selectionCriteria: 'Business idea, entrepreneurial potential',
    officialLink: 'https://thielfellowship.org/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '33',
    name: 'Y Combinator Startup School',
    organizer: 'Y Combinator',
    description: 'Free online startup school with courses, office hours, and community.',
    category: 'fellowship',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-01-01'),
    applicationEnd: new Date('2025-12-31'),
    eventStart: new Date('2025-01-01'),
    eventEnd: new Date('2025-12-31'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['Aspiring entrepreneurs', 'Startup founders'],
    techStack: ['Any'],
    domains: ['Entrepreneurship', 'Startups'],
    prizes: 'Free courses, community access',
    officialLink: 'https://www.startupschool.org/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '34',
    name: 'Techstars Startup Accelerator',
    organizer: 'Techstars',
    description: '3-month accelerator program providing mentorship, funding, and resources.',
    category: 'fellowship',
    mode: 'hybrid',
    level: 'advanced',
    applicationStart: new Date('2025-01-01'),
    applicationEnd: new Date('2025-03-31'),
    eventStart: new Date('2025-06-01'),
    eventEnd: new Date('2025-09-01'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['Early-stage startups', 'Founding team'],
    techStack: ['Any'],
    domains: ['Entrepreneurship', 'Startups'],
    stipend: '$20,000 + $100,000 convertible note',
    selectionCriteria: 'Business model, team, market potential',
    officialLink: 'https://www.techstars.com/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '35',
    name: 'Google Developer Student Clubs',
    organizer: 'Google',
    description: 'Community groups for students interested in Google developer technologies.',
    category: 'fellowship',
    mode: 'hybrid',
    level: 'beginner',
    applicationStart: new Date('2025-01-01'),
    applicationEnd: new Date('2025-12-31'),
    eventStart: new Date('2025-01-01'),
    eventEnd: new Date('2025-12-31'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['University students', 'Interest in Google technologies'],
    techStack: ['Android', 'Flutter', 'Firebase', 'TensorFlow'],
    domains: ['Mobile Development', 'AI/ML', 'Web Development'],
    prizes: 'Swag, certificates, community access',
    officialLink: 'https://developers.google.com/community/gdsc',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '36',
    name: 'Microsoft Learn Student Ambassadors',
    organizer: 'Microsoft',
    description: 'Program for students to build technical skills and lead tech communities.',
    category: 'fellowship',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-01-01'),
    applicationEnd: new Date('2025-12-31'),
    eventStart: new Date('2025-01-01'),
    eventEnd: new Date('2025-12-31'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['University students', 'Community leadership interest'],
    techStack: ['Azure', 'Power Platform', 'Microsoft 365'],
    domains: ['Cloud Computing', 'DevOps'],
    prizes: 'Swag, certifications, event support',
    officialLink: 'https://studentambassadors.microsoft.com/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  // More Hackathons
  {
    id: '37',
    name: 'HackPrinceton',
    organizer: 'Princeton University',
    description: 'Princeton\'s annual hackathon bringing together students from across the globe.',
    category: 'hackathon',
    mode: 'offline',
    level: 'intermediate',
    applicationStart: new Date('2025-08-01'),
    applicationEnd: new Date('2025-09-30'),
    eventStart: new Date('2025-11-08'),
    eventEnd: new Date('2025-11-10'),
    location: 'Princeton University, NJ',
    country: 'USA',
    isIndiaFocused: false,
    eligibility: ['University students', 'Travel reimbursements'],
    techStack: ['Any'],
    domains: ['Web Development', 'AI/ML', 'Mobile Development'],
    prizes: '$20,000+ in prizes',
    officialLink: 'https://hackprinceton.com/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '38',
    name: 'HackIIITD',
    organizer: 'IIIT Delhi',
    description: 'IIIT Delhi\'s annual hackathon promoting innovation and problem-solving.',
    category: 'hackathon',
    mode: 'offline',
    level: 'intermediate',
    applicationStart: new Date('2025-09-01'),
    applicationEnd: new Date('2025-10-15'),
    eventStart: new Date('2025-11-22'),
    eventEnd: new Date('2025-11-24'),
    location: 'IIIT Delhi, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['College students', 'Teams of 2-4'],
    techStack: ['Any'],
    domains: ['Web Development', 'AI/ML', 'IoT'],
    prizes: '₹2,00,000+ in prizes',
    officialLink: 'https://hackiiitd.tech/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '39',
    name: 'Hack the Valley',
    organizer: 'University of Toronto',
    description: 'Canada\'s largest student-run hackathon.',
    category: 'hackathon',
    mode: 'offline',
    level: 'intermediate',
    applicationStart: new Date('2025-07-15'),
    applicationEnd: new Date('2025-09-15'),
    eventStart: new Date('2025-10-18'),
    eventEnd: new Date('2025-10-20'),
    location: 'University of Toronto, Canada',
    country: 'Canada',
    isIndiaFocused: false,
    eligibility: ['University students', 'Travel support available'],
    techStack: ['Any'],
    domains: ['Web Development', 'AI/ML', 'Mobile Development'],
    prizes: '$30,000+ in prizes',
    officialLink: 'https://hackthevalley.io/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '40',
    name: 'HackJMI',
    organizer: 'Jamia Millia Islamia',
    description: '36-hour hackathon at JMI promoting innovation and entrepreneurship.',
    category: 'hackathon',
    mode: 'offline',
    level: 'beginner',
    applicationStart: new Date('2025-09-15'),
    applicationEnd: new Date('2025-10-30'),
    eventStart: new Date('2025-11-29'),
    eventEnd: new Date('2025-12-01'),
    location: 'JMI, New Delhi, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['College students', 'Teams of 2-4'],
    techStack: ['Any'],
    domains: ['Web Development', 'AI/ML', 'Mobile Development'],
    prizes: '₹1,50,000+ in prizes',
    officialLink: 'https://hackjmi.tech/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  // More Internships
  {
    id: '41',
    name: 'Intuit Internship',
    organizer: 'Intuit',
    description: 'Software engineering internship working on financial software products.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-03-31'),
    eventStart: new Date('2025-05-15'),
    eventEnd: new Date('2025-08-15'),
    location: 'Bangalore, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Strong CS fundamentals'],
    techStack: ['Java', 'React', 'Node.js', 'AWS'],
    domains: ['Web Development', 'Fintech'],
    stipend: '₹55,000-75,000/month',
    selectionCriteria: 'Coding test, technical interviews',
    officialLink: 'https://www.intuit.com/careers/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '42',
    name: 'PayPal Internship',
    organizer: 'PayPal',
    description: 'Technology internship in payment solutions and fintech.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-01-15'),
    applicationEnd: new Date('2025-03-15'),
    eventStart: new Date('2025-05-01'),
    eventEnd: new Date('2025-08-31'),
    location: 'Chennai, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Strong problem-solving'],
    techStack: ['Java', 'Python', 'React', 'Kubernetes'],
    domains: ['Web Development', 'Fintech', 'Systems Programming'],
    stipend: '₹65,000-85,000/month',
    selectionCriteria: 'Online assessment, interviews',
    officialLink: 'https://www.paypal.com/us/webapps/mpp/jobs',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '43',
    name: 'Salesforce Internship',
    organizer: 'Salesforce',
    description: 'Software engineering internship working on CRM and cloud platforms.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-03-31'),
    eventStart: new Date('2025-05-15'),
    eventEnd: new Date('2025-08-15'),
    location: 'Hyderabad, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Strong CS fundamentals'],
    techStack: ['Java', 'Apex', 'React', 'Salesforce'],
    domains: ['Web Development', 'Cloud Computing'],
    stipend: '₹60,000-80,000/month',
    selectionCriteria: 'Coding rounds, technical interviews',
    officialLink: 'https://www.salesforce.com/company/careers/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '44',
    name: 'VMware Internship',
    organizer: 'VMware',
    description: 'Software engineering internship in virtualization and cloud infrastructure.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-01-15'),
    applicationEnd: new Date('2025-03-15'),
    eventStart: new Date('2025-05-01'),
    eventEnd: new Date('2025-08-31'),
    location: 'Bangalore, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E./M.Tech students', 'Systems programming interest'],
    techStack: ['C++', 'Python', 'Go', 'Kubernetes'],
    domains: ['Systems Programming', 'Cloud Computing', 'DevOps'],
    stipend: '₹70,000-90,000/month',
    selectionCriteria: 'Technical interviews, system design',
    officialLink: 'https://careers.vmware.com/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '45',
    name: 'Oracle Internship',
    organizer: 'Oracle',
    description: 'Software engineering internship working on database and cloud technologies.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-03-31'),
    eventStart: new Date('2025-05-15'),
    eventEnd: new Date('2025-08-15'),
    location: 'Bangalore, Hyderabad',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Database interest'],
    techStack: ['Java', 'SQL', 'Python', 'Oracle Cloud'],
    domains: ['Database', 'Cloud Computing', 'Systems Programming'],
    stipend: '₹55,000-75,000/month',
    selectionCriteria: 'Coding test, technical interviews',
    officialLink: 'https://www.oracle.com/careers/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '46',
    name: 'SAP Internship',
    organizer: 'SAP',
    description: 'Technology internship in enterprise software and business solutions.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-01-15'),
    applicationEnd: new Date('2025-03-15'),
    eventStart: new Date('2025-05-01'),
    eventEnd: new Date('2025-08-31'),
    location: 'Bangalore, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Enterprise software interest'],
    techStack: ['Java', 'ABAP', 'JavaScript', 'SAP Cloud'],
    domains: ['Enterprise Software', 'Web Development'],
    stipend: '₹50,000-70,000/month',
    selectionCriteria: 'Online assessment, interviews',
    officialLink: 'https://www.sap.com/careers/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '47',
    name: 'Nutanix Internship',
    organizer: 'Nutanix',
    description: 'Software engineering internship in hyperconverged infrastructure.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-03-31'),
    eventStart: new Date('2025-05-15'),
    eventEnd: new Date('2025-08-15'),
    location: 'Bangalore, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E./M.Tech students', 'Systems interest'],
    techStack: ['C++', 'Python', 'Go'],
    domains: ['Systems Programming', 'Cloud Computing'],
    stipend: '₹65,000-85,000/month',
    selectionCriteria: 'Coding rounds, technical interviews',
    officialLink: 'https://www.nutanix.com/company/careers',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '48',
    name: 'Zomato Internship',
    organizer: 'Zomato',
    description: 'Technology internship working on food delivery and restaurant tech platforms.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-02-15'),
    applicationEnd: new Date('2025-04-15'),
    eventStart: new Date('2025-05-15'),
    eventEnd: new Date('2025-08-15'),
    location: 'Gurgaon, Bangalore',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Strong CS fundamentals'],
    techStack: ['Python', 'React', 'Node.js', 'MongoDB'],
    domains: ['Web Development', 'Mobile Development', 'Data Science'],
    stipend: '₹45,000-65,000/month',
    selectionCriteria: 'Coding challenge, technical interviews',
    officialLink: 'https://www.zomato.com/careers',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '49',
    name: 'Swiggy Internship',
    organizer: 'Swiggy',
    description: 'Software engineering internship in food tech and logistics.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-04-01'),
    eventStart: new Date('2025-05-01'),
    eventEnd: new Date('2025-08-31'),
    location: 'Bangalore, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Problem-solving skills'],
    techStack: ['Python', 'React', 'Go', 'PostgreSQL'],
    domains: ['Web Development', 'Mobile Development', 'Data Science'],
    stipend: '₹40,000-60,000/month',
    selectionCriteria: 'Online coding test, interviews',
    officialLink: 'https://careers.swiggy.com/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '50',
    name: 'PhonePe Internship',
    organizer: 'PhonePe',
    description: 'Technology internship in digital payments and fintech solutions.',
    category: 'internship',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-02-15'),
    applicationEnd: new Date('2025-04-15'),
    eventStart: new Date('2025-05-15'),
    eventEnd: new Date('2025-08-15'),
    location: 'Bangalore, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['B.Tech/B.E. students', 'Strong CS fundamentals'],
    techStack: ['Java', 'Kotlin', 'React', 'PostgreSQL'],
    domains: ['Mobile Development', 'Fintech', 'Web Development'],
    stipend: '₹50,000-70,000/month',
    selectionCriteria: 'Coding rounds, technical interviews',
    officialLink: 'https://www.phonepe.com/careers/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
];

export const getOpportunityStatus = (opp: Opportunity): 'upcoming' | 'ongoing' | 'past' => {
  const now = new Date();
  if (now < opp.applicationStart) return 'upcoming';
  if (now > opp.eventEnd) return 'past';
  return 'ongoing';
};

export const getDaysUntilDeadline = (deadline: Date): number => {
  const now = new Date();
  const diff = deadline.getTime() - now.getTime();
  return Math.ceil(diff / (1000 * 60 * 60 * 24));
};

/**
 * Filter out expired opportunities - only return upcoming or ongoing ones
 */
export const getActiveOpportunities = (opportunities: Opportunity[]): Opportunity[] => {
  const now = new Date();
  return opportunities.filter(opp => {
    // Keep if application hasn't ended yet or event hasn't ended yet
    return opp.applicationEnd >= now || opp.eventEnd >= now;
  });
};
