import { Opportunity } from '@/types/opportunity';

export const mockOpportunities: Opportunity[] = [
  {
    id: '1',
    name: 'Google Summer of Code 2025',
    organizer: 'Google',
    description: 'A global, online program focused on bringing new contributors into open source software development. GSoC Contributors work with an open source organization on a 12+ week programming project.',
    category: 'opensource',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-03-10'),
    applicationEnd: new Date('2025-04-02'),
    eventStart: new Date('2025-05-27'),
    eventEnd: new Date('2025-08-25'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['18+ years old', 'Enrolled in post-secondary education', 'First-time or returning contributor'],
    techStack: ['Various'],
    domains: ['Open Source', 'Web Development', 'AI/ML', 'Systems Programming'],
    stipend: '$1,500 - $6,600 based on project size',
    selectionCriteria: 'Proposal quality, contributions to org, communication skills',
    officialLink: 'https://summerofcode.withgoogle.com/',
    applicationLink: 'https://summerofcode.withgoogle.com/',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Google_Summer_of_Code_logo_%282023%29.png/220px-Google_Summer_of_Code_logo_%282023%29.png',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '9',
    name: 'Google STEP Internship (India)',
    organizer: 'Google',
    description:
      'Summer Trainee Engineering Program (STEP) for first and second year undergraduate students interested in software engineering.',
    category: 'internship',
    mode: 'hybrid',
    level: 'beginner',
    applicationStart: new Date('2025-01-01'),
    applicationEnd: new Date('2025-02-15'),
    eventStart: new Date('2025-05-01'),
    eventEnd: new Date('2025-07-31'),
    location: 'Bangalore / Hyderabad',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['First or second year B.Tech/B.E. students', 'Strong programming fundamentals'],
    techStack: ['C++', 'Java', 'Python'],
    domains: ['Systems Programming', 'Web Development'],
    stipend: 'Competitive internship stipend',
    selectionCriteria: 'Online assessments and interviews',
    officialLink: 'https://careers.google.com/programs/step/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '10',
    name: 'GitHub Campus Expert',
    organizer: 'GitHub',
    description:
      'Program for student leaders to build technical communities on campus with training, resources, and mentorship.',
    category: 'fellowship',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-03-01'),
    applicationEnd: new Date('2025-03-31'),
    eventStart: new Date('2025-04-15'),
    eventEnd: new Date('2025-10-15'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['University students', 'Active in campus community'],
    techStack: ['Git', 'GitHub'],
    domains: ['Open Source', 'DevOps'],
    prizes: 'Training, swag, community budget',
    selectionCriteria: 'Application, video, community impact',
    officialLink: 'https://education.github.com/experts',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '11',
    name: 'ETHIndia',
    organizer: 'Devfolio',
    description:
      'India’s premier Ethereum hackathon bringing builders together to work on DeFi, DAOs, and Web3.',
    category: 'hackathon',
    mode: 'offline',
    level: 'intermediate',
    applicationStart: new Date('2025-08-01'),
    applicationEnd: new Date('2025-09-01'),
    eventStart: new Date('2025-12-05'),
    eventEnd: new Date('2025-12-07'),
    location: 'Bengaluru, India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['Students and professionals', 'Solo or team participation'],
    techStack: ['Solidity', 'Ethereum', 'Web3'],
    domains: ['Blockchain'],
    prizes: '$100,000+ in prizes and grants',
    selectionCriteria: 'Project innovation, technical depth, usefulness',
    officialLink: 'https://ethindia.co/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '12',
    name: 'Google Cloud Ready Facilitator Program',
    organizer: 'Google Cloud',
    description:
      'Hands-on program for students in India to learn Google Cloud through quests, labs, and swags.',
    category: 'fellowship',
    mode: 'online',
    level: 'beginner',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-02-28'),
    eventStart: new Date('2025-03-15'),
    eventEnd: new Date('2025-06-15'),
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['College students in India'],
    techStack: ['Google Cloud', 'Kubernetes', 'BigQuery'],
    domains: ['Cloud Computing', 'Data Science'],
    prizes: 'Swag, certificates, leaderboard recognition',
    selectionCriteria: 'Completion of labs and quests',
    officialLink: 'https://events.withgoogle.com/google-cloud-ready-facilitator-program/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '2',
    name: 'MLH Global Hack Week',
    organizer: 'Major League Hacking',
    description: 'A week-long celebration of hacking with daily challenges, workshops, and mini-hackathons. Connect with hackers worldwide and build cool projects!',
    category: 'hackathon',
    mode: 'online',
    level: 'beginner',
    applicationStart: new Date('2025-01-15'),
    applicationEnd: new Date('2025-02-01'),
    eventStart: new Date('2025-02-03'),
    eventEnd: new Date('2025-02-09'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['Students', 'Recent graduates'],
    techStack: ['Any'],
    domains: ['Web Development', 'AI/ML', 'Game Development'],
    prizes: 'Swag, prizes for daily challenges',
    officialLink: 'https://ghw.mlh.io/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '3',
    name: 'Smart India Hackathon 2025',
    organizer: 'Ministry of Education, India',
    description: 'India\'s largest hackathon aimed at solving real-world problems faced by various ministries and departments of the government.',
    category: 'hackathon',
    mode: 'hybrid',
    level: 'intermediate',
    applicationStart: new Date('2025-06-01'),
    applicationEnd: new Date('2025-07-15'),
    eventStart: new Date('2025-12-01'),
    eventEnd: new Date('2025-12-02'),
    location: 'Multiple nodal centers across India',
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['Engineering students', 'Teams of 6 members'],
    techStack: ['Various'],
    domains: ['IoT', 'AI/ML', 'Web Development', 'Mobile Development'],
    prizes: '₹1,00,000 per winning team',
    selectionCriteria: 'Innovation, feasibility, impact, technical complexity',
    officialLink: 'https://www.sih.gov.in/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '4',
    name: 'GitHub Externship',
    organizer: 'GitHub',
    description: 'A 3-month remote externship program for students in India to work on open-source projects with GitHub mentors.',
    category: 'internship',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-02-01'),
    applicationEnd: new Date('2025-02-28'),
    eventStart: new Date('2025-04-01'),
    eventEnd: new Date('2025-06-30'),
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['Engineering students in India', '2nd or 3rd year preferred'],
    techStack: ['Git', 'GitHub', 'Various programming languages'],
    domains: ['Open Source', 'DevOps', 'Web Development'],
    stipend: '₹50,000/month',
    selectionCriteria: 'GitHub profile, open source contributions, technical skills',
    officialLink: 'https://github.com/externship',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '5',
    name: 'LFX Mentorship Program',
    organizer: 'Linux Foundation',
    description: 'A remote mentorship program where participants gain real-world experience working on open source projects.',
    category: 'opensource',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-02-15'),
    applicationEnd: new Date('2025-03-15'),
    eventStart: new Date('2025-06-01'),
    eventEnd: new Date('2025-08-31'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['18+ years old', 'Students or professionals'],
    techStack: ['Kubernetes', 'Cloud Native', 'Linux'],
    domains: ['Open Source', 'Cloud Computing', 'DevOps'],
    stipend: '$3,000 - $6,600',
    officialLink: 'https://lfx.linuxfoundation.org/tools/mentorship/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '6',
    name: 'Outreachy',
    organizer: 'Software Freedom Conservancy',
    description: 'Internships in open source and open science for people subject to systemic bias and underrepresented in tech.',
    category: 'fellowship',
    mode: 'online',
    level: 'beginner',
    applicationStart: new Date('2025-01-15'),
    applicationEnd: new Date('2025-02-25'),
    eventStart: new Date('2025-05-26'),
    eventEnd: new Date('2025-08-22'),
    country: 'Worldwide',
    isIndiaFocused: false,
    eligibility: ['Underrepresented groups in tech', 'New to open source welcome'],
    techStack: ['Various'],
    domains: ['Open Source', 'Web Development', 'Data Science'],
    stipend: '$7,000',
    selectionCriteria: 'Contribution period performance, proposal quality',
    officialLink: 'https://www.outreachy.org/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '7',
    name: 'HackMIT 2025',
    organizer: 'MIT',
    description: 'MIT\'s annual hackathon bringing together 1000+ hackers to build creative projects over 24 hours.',
    category: 'hackathon',
    mode: 'offline',
    level: 'advanced',
    applicationStart: new Date('2025-07-01'),
    applicationEnd: new Date('2025-08-15'),
    eventStart: new Date('2025-09-20'),
    eventEnd: new Date('2025-09-21'),
    location: 'MIT Campus, Cambridge, MA',
    country: 'USA',
    isIndiaFocused: false,
    eligibility: ['University students worldwide', 'Travel reimbursements available'],
    techStack: ['Any'],
    domains: ['AI/ML', 'Web Development', 'Mobile Development', 'Blockchain'],
    prizes: '$10,000+ in prizes',
    officialLink: 'https://hackmit.org/',
    featured: false,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: '8',
    name: 'Microsoft ENGAGE',
    organizer: 'Microsoft',
    description: 'A mentorship program for Indian engineering students to learn from Microsoft engineers and build projects.',
    category: 'internship',
    mode: 'online',
    level: 'intermediate',
    applicationStart: new Date('2025-04-01'),
    applicationEnd: new Date('2025-04-30'),
    eventStart: new Date('2025-05-15'),
    eventEnd: new Date('2025-07-15'),
    country: 'India',
    isIndiaFocused: true,
    eligibility: ['2nd/3rd year engineering students in India'],
    techStack: ['Azure', 'C#', '.NET', 'React'],
    domains: ['Cloud Computing', 'AI/ML', 'Web Development'],
    selectionCriteria: 'Resume screening, coding assessment, interviews',
    officialLink: 'https://microsoft.acehacker.com/',
    featured: true,
    verified: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
];

export const getOpportunityStatus = (opp: Opportunity): 'upcoming' | 'ongoing' | 'past' => {
  const now = new Date();
  if (now < opp.applicationStart) return 'upcoming';
  if (now > opp.eventEnd) return 'past';
  return 'ongoing';
};

export const getDaysUntilDeadline = (deadline: Date): number => {
  const now = new Date();
  const diff = deadline.getTime() - now.getTime();
  return Math.ceil(diff / (1000 * 60 * 60 * 24));
};
